### ISSUE TITLE
`--data` is not working

### ISSUE THREAD

**Issue by zachguo** [fitnr/taft#4]
Thanks for this module! Really clean and efficient!

But it seems that `--data` is not working.

``` html
<!-- test.hbs -->
<p>{{title}}</p>
```

``` json
#index.json
{
  "title": "UP"
}
```

```
> ./node_modules/taft/bin/taft.js --data index.json test.hbs
building: test.hbs
<p></p>
```

```
> echo '{"title":"UP"}' | ./node_modules/taft/bin/taft.js --data - test.hbs
Problem reading data file: -
Didn't recognize file type 
building: test.hbs
<p></p>
```

YAML front matter is working fine, taft v0.2.2

**Comment by fitnr** [comment]
I've reproduced the problem and will have a fix ready soon. In the mean time, the following works:

```
> taft --data index.json test.hbs
building: test.hbs
<p>UP</p>
```

However, `taft` will place the `title` variable in an object named `index`, so you'll need to change `test.hbs` slightly:

```
<p>{{index.title}}</p>
```

**Comment by zachguo** [comment]
Thanks for your reply.
I'm using taft to generate htmls based on different data jsons but a same template. So, instead of changing the template, I gonna `cat` each json and feed it to taft via `--data -`

**Comment by fitnr** [comment]
I agree that what you want to do should work! I should have a fix ready in the next couple of hours.

**Comment by zachguo** [comment]
I really appreciate it!
Could you publish latest version to npm?

**Comment by fitnr** [comment]
Soon! I found a couple of other bugs I'd like to fix :)

**Comment by fitnr** [comment]
@zachguo It's published. v0.3.0

**Comment by zachguo** [comment]
thx! :tada:

**Comment by fitnr** [comment]
Thanks for using the library! I'm glad it's useful for someone besides me.

**Comment by jacksongoode** [comment]
@fitnr I believe this is still an issue with the present version. I was able to reproduce the original bug test.
