### ISSUE TITLE
could u pls provide a demo blog source on github.com?

### ISSUE THREAD

**Issue by luckypoem** [fitnr/taft#5]
hi.
i installed taft by "npm install -g taft",

**Comment by fitnr** [comment]
Have you looked at this page on the wiki?
https://github.com/fitnr/taft/wiki/Basic-blog-like-layout

If it's unclear, I'm happy to expand or clarify.

**Comment by luckypoem** [comment]
hi.

still unclear for me.
could u pls consider publishing a demo blog repo on github.com?
that will be more convenient for users.

thank u very much

**Comment by fitnr** [comment]
OK, see: https://github.com/fitnr/taft-demo-site

**Comment by luckypoem** [comment]
hi.

i setup a blog: http://taft.smt.biz.st/ ,some questions:

1.the About page's link: http://taft.smt.biz.st/www/about.html
the Contact page's link: http://taft.smt.biz.st/www/contact.html
the Welcome pages link: http://taft.smt.biz.st/www/index.html
Taft demo site link: http://taft.smt.biz.st/www/index.html
are all wrong.how to fix them?
(the correct ones are:
http://taft.smt.biz.st/about.html
http://taft.smt.biz.st/contact.html
http://taft.smt.biz.st/index.html 
http://taft.smt.biz.st/index.html )

2.the latest published post should be on the top,the earliest published post should be  in the bottom.right?but the reality is just the reverse.how to correct it?
1. the source post's content below YAML front matter must be in html code as the source post's file format is html.it's a little inconvenient. so how to enable Markdown posts?
2. how to paginate?

thank u.

**Comment by fitnr** [comment]
Make sure that you're using the newest version of Taft (`npm up [-g] taft`) and try again.
